### PR TITLE
Add new version to Flatpak AppData

### PR DESCRIPTION
**Pull request by AsciiWolf**
One more PR. :-) @f4exb Feel free to review and merge.

### CODE REVIEW

**Comment by AsciiWolf** [comment]
Anyway, I am not sure if it is ideal to manually update the AppData file every time a new version is released + the AppData file in a stable release will be always outdated anyway. Another possible solution is removing the releases tag completely - it is not required and the Flatpak would be usually built from latest Git code anyway. @f4exb Let me know what approach would you prefer.

**Comment by f4exb** [comment]
No way I will drop tagging as I consider it essential. It is up to you to find a way to make it automatic in your AppData file.

**Comment by AsciiWolf** [comment]
Wait, of course I didn't mean Git tags. :-) I was talking about the `<releases>` tag in AppData file.

**Comment by f4exb** [comment]
Ok

**Comment by AsciiWolf** [comment]
I have just sent #428 that removes releases from Flatpak's AppData file. Feel free to merge it instead of this PR.

**Comment by f4exb** [comment]
PR rejected in favor of #428

**Pull request closed without merging**
