### PR TITLE
Spectrum measurements

### PR DESCRIPTION
**Pull request by srcejon**
This PR changes the Peak measurement patch, to add several different selectable spectrum measurements, including:

- Peak
- Channel power
- Adjacent channel power
- SNR
- SNFR
- THD
- THD+N
- SINAD
- SFDR
- (and None, for no measurement)

See the files changed for some example images and docs.

Note that I haven't yet changed the precision used for the peak, as I wanted the exact bin frequency, and you can't get this from the markers (it seems the spectrum isn't quite plotted on the bin frequency) - so I'll address that in a later patch. But for now, this at least restores the old appearance.

### CODE REVIEW

**Comment by f4exb** [comment]
I think the functionality is interesting but this is not something everyone will use every day so we have to think of something less prominent in the GUI.

**Comment by srcejon** [comment]
How about a simple measurements toggle icon in the controls GUI, that shows/hides a measurements widget that opens to the side as you suggest? 

That would also have the benefit of being able to display SNR/THD/SINAD simultaneously which would be preferable anyway (along with a peak table, and a few other goodies I was thinking of adding later).

**Comment by f4exb** [comment]
This is how it looks like when spectrum display is minimized:
image

I think it needs a bit of refinement...

**Comment by f4exb** [comment]
This could also be a Rx channel on its own as we already have the Channel Analyzer.

**Comment by f4exb** [comment]
We definitely need more space for display and control. See this for source of inspiration: https://www.youtube.com/watch?v=ypu5glggyLI

**Comment by f4exb** [comment]
The resolution bandwidth us already displayed as a tool-tip over the FFT size selection combo box.

**Comment by srcejon** [comment]
> This could also be a Rx channel on its own as we already have the Channel Analyzer.

But I would like the measurements to be available for all spectrum views. They're not all applicable in every case, but channel power can be used for TX, and THD might be used for audio spectra, etc.

**Comment by f4exb** [comment]
OK... that's a valid point and there is a spectrum display in the channel analyzer anyway so this can be used to isolate that spectrum display from the main spectrum avoiding collision with the other spectrum overlays like the channel markers.

**Comment by srcejon** [comment]
Sounds good - I'll do an updated patch.

**Pull request merged**
