### PR TITLE
Add SDRPlay RSP1B

### PR DESCRIPTION
**Pull request by wysiwyng**
Adds support for the new RSP1B. I tried to add it wherever I found references to other SDRPlay devices, feel free to edit or message me if I missed something.

### CODE REVIEW

**Comment by f4exb** [comment]
Ubuntu build fails because of  SDRplay API V3.14. Is the upgrade to 3.14 necessary?

**Comment by wysiwyng** [comment]
to support the RSP1B, yes: https://www.sdrplay.com/api/

**Comment by srcejon** [comment]
Ok, I see the failure now. Will try to fix.

**Comment by srcejon** [comment]
Here's the PR for sdrangel-windows-libraries https://github.com/f4exb/sdrangel-windows-libraries/pull/20

**Comment by srcejon** [comment]
@wysiwyng can you add another change to this please?

In cmake/ci/build_sdrplay.sh, please change:

    sudo yes | sh install_lib.sh

To 

    sudo yes | bash install_lib.sh

**Comment by srcejon** [comment]
I think the external/windows link needs updating to the latest hash.

**Pull request merged**
