### PR TITLE
Add Costas loop PLL to channel analyzer

### PR DESCRIPTION
**Pull request by srcejon**
This patch:

- Adds a Costas loop PLL to the channel analyzer
- Adds loop bandwidth and other PLL controls to Channel Analyzer GUI.
- Fixes bug where PLL lock frequency is incorrectly scaled by the decimation factor.

Costas loop should somewhat combine existing PLL and FLL functionality, providing both frequency and phase lock. Seems to provide a more stable lock too in the brief testing I've done.  
Happy to change the way the GUI hides the extra widgets when PLL is disabled, if you don't like it, but I thought that would keep the GUI a bit simpler in most use cases where the PLL isn't being used.

### CODE REVIEW

**Comment by f4exb** [comment]
If I understand right this is an new extra kind of PLL not a replacement of the existing one and thus an extension of the capabilities. Am I correct?

**Comment by srcejon** [comment]
Yep - original PLL and FLL remain. You can choose between one of the 3 via a drop-down.

 The damping factor and loop gain controls I've added are only for the original PLL. I found some slight tweaking of these values can improve the lock. You might want to review the range of the controls.

**Comment by srcejon** [comment]
Here's a pic

SigAnPLL

The new PLL row of controls is only visible when the padlock icon is pressed.

**Comment by f4exb** [comment]
There is an error in Qt 5.11 (Docker image):
```
'PlaceholderText' is not a member of 'QPalette'
```
I vaguely remember this has been encountered before.

**Pull request merged**
