### PR TITLE
Add DAB/DAB+ demodulator

### PR DESCRIPTION
**Pull request by srcejon**
Hi,

This PR adds a DAB/DAB+ demodulator to address #169. 

It should work on both Windows and Linux, however, it seems there is a base SDRangel issue on Windows which can cause it not to work in some instances (SampleSinkFifo::write: overflow when there are no demodulators). I'll file a bug for that later.

Fairly basic for now.

### CODE REVIEW

**Comment by srcejon** [comment]
To build on windows, an update to sdrangel-windows-libraries is needed: https://github.com/f4exb/sdrangel-windows-libraries/pull/9

**Comment by f4exb** [comment]
It looks like the Ubuntu build in Appveyor is failing because it creates `libdab_lib.so` while it expects `libdab.so` later:
```
[00:08:02] [39/39] Linking CXX shared library /home/appveyor/projects/sdrangel/obj-x86_64-linux-gnu/external/lib/libdab_lib.so
```
then
```
[00:23:19] /usr/bin/ld: cannot find -ldab
```
I don't know why this `_lib` suffix is appended. I suppose this should be for MSVC.

**Comment by srcejon** [comment]
Thanks. It's odd, but that's just what the DAB library author called it, which was written for Linux (My fork to make it compile with MSVC didn't change it).  I just used the wrong name in external/CMakeLists.txt. Hopefully fixed now.

**Comment by f4exb** [comment]
Never mind the odd name. It works!

**Pull request merged**
