### PR TITLE
Add 3D Map

### PR DESCRIPTION
**Pull request by srcejon**
New dependencies qtwebengine5-dev and qtbase5-private-dev.
You may need to build that latest version of aptdec.

APT Demod Updates

Add projection of image on to 3D map.
Add support for temperature map.
Add support for colour palettes for image enhancements.
Fix IR channel names.

ADS-B Demod Updates

Add support for animated 3D models.
Downloaded zipped airplane database.
Add table context menu.
Add airline and country images to text bubbles on maps.
Fix calculation of ground speed when on surface.
Fix position calculation when aircraft transistions from surface to air.
Fix altitude calculation when Q-bit is set.
Speed up processing of large log files.
Add new airline logos.

AIS update

Add support for 3D models.
Remove vessels from table if not heard from in last 10 minutes.
Add columns in table for vessel length, time last position & message were received and number of messages received.
Add context menu.

Satellite Tracker updates

Add support for replaying of passes in the past, where current time is determined from File Input device.
Add latitude and longitude to satellite data table.
Update ground track generation to better work with 3D map.
Add support for 3D models.
Add Cubesat image for 2D map.
Send LOS to other plugins, when no device settings are setup.
Pass TLEs to other plugins, so they can use a consistent copy for replays.

### CODE REVIEW

**Comment by srcejon** [comment]
Looks like they have switched to Visual Studio 2022

**Comment by f4exb** [comment]
Indeed: `-- MSVC_VERSION is 1930`
I will try a patch of CMakeLists.txt and see what happens...

**Comment by f4exb** [comment]
However this is broken in the Ubuntu build:
```
../plugins/channelrx/demodapt/aptdemodimageworker.cpp: In member function ‘void APTDemodImageWorker::calcCoord(int)’:
../plugins/channelrx/demodapt/aptdemodimageworker.cpp:388:24: error: no match for ‘operator[]’ (operand types are ‘Tle’ and ‘int’)
  388 |             Tle tle(tle[0].toStdString(), tle[1].toStdString(), tle[2].toStdString());
      |                        ^
../plugins/channelrx/demodapt/aptdemodimageworker.cpp:388:46: error: no match for ‘operator[]’ (operand types are ‘Tle’ and ‘int’)
  388 |             Tle tle(tle[0].toStdString(), tle[1].toStdString(), tle[2].toStdString());
      |                                              ^
../plugins/channelrx/demodapt/aptdemodimageworker.cpp:388:68: error: no match for ‘operator[]’ (operand types are ‘Tle’ and ‘int’)
  388 |             Tle tle(tle[0].toStdString(), tle[1].toStdString(), tle[2].toStdString());
      |  
```

**Comment by f4exb** [comment]
For what concerns MSVC you can rebase on `master` it works... https://github.com/f4exb/sdrangel/actions/runs/1799233101

**Comment by srcejon** [comment]
Should have fixed the Linux compilation error above.

The current Windows problem seems to be that Qt WebEngine isn't being installed. This is an optional Qt component like Qt Charts. I don't know how to fix this. The .appveyor.yml in the root directory only appears to be for Linux.

**Pull request merged**
