### PR TITLE
RTL-SDR: Adjust sample rate limits

### PR DESCRIPTION
**Pull request by kasper93**

### CODE REVIEW

**Comment by kasper93** [comment]
Set same limits as in librtlsdr https://github.com/osmocom/rtl-sdr/blob/ed0317e6a58c098874ac58b769cf2e609c18d9a5/include/rtl-sdr.h#L261-L262 

The original limit of 2.4MS/s is there because above that it _may_ be unstable. But it hardware dependent and we shouldn't limit this is software. I use 2.56MS/s in all other software and people use even more without any drops or other issues. Just want to get rid of this artificial limitation.

**Comment by f4exb** [comment]
Makes sense. I have thought of doing this but lost track. Thanks for contributing!

**Comment by kasper93** [comment]
@f4exb: What happened with this? It got merged into dev, but is lost now. It didn't work well?

**Comment by f4exb** [comment]
True and I don't know what happened fortunately nothing gets lost with git. I will re-apply it.

**Pull request merged**
