### PR TITLE
Install SoapySDR support modules and UHD DLL on Windows

### PR DESCRIPTION
**Pull request by srcejon**
This would enable out-of-the-box support for some additional radios (such as USRP radios).

This depends on the following pull request https://github.com/f4exb/sdrangel-windows-libraries/pull/2 which includes the actual DLLs.

### CODE REVIEW

**Comment by alphafox02** [comment]
Sounds great. Don’t suppose this looks for already existing installed soapy libs and/or adds Linux soapy support?

**Comment by alphafox02** [comment]
Disregard - it says Windows right there in the title.

**Comment by srcejon** [comment]
Linux build instructions are here: https://github.com/f4exb/sdrangel/issues/617

**Comment by alphafox02** [comment]
Thank you. I had previously built manually and had my b205mini mini working. I was just hoping it maybe I thought the .deb package either had what’s needed included or that maybe somehow it would reference and use the uhd/soapy that’s already preinstalled.

**Pull request merged**
