### PR TITLE
Add USRP radio source & sink plugins

### PR DESCRIPTION
**Pull request by srcejon**
This PR adds USRP sample source and sink plugins, adding support for these https://www.ettus.com/products/ SDRs.
Tested with a B210 on Windows and Linux, but should work with other devices. Seems to work better than the SoapySDR plugin, which crashes a lot. It requires the UHD library.

### CODE REVIEW

**Comment by srcejon** [comment]
I've added the UHD library to sdrangel-windows-library project.
On Linux, UHD can be built as described here: https://github.com/f4exb/sdrangel/issues/617 and then when running cmake pass -DUHD_DIR=/opt/install/uhd

**Comment by srcejon** [comment]
It seems the Linux build is failing due to a missing Python module called mako.

According to UHD build instructions, https://files.ettus.com/manual/page_build_guide.html, this is just required at build time.

This can be installed with 'sudo apt install python3-pip' then 'pip3 install mako'

Might also need:

pip3 install requests 
pip3 install numpy

The Windows build needs: https://github.com/f4exb/sdrangel-windows-libraries/pulls

**Comment by f4exb** [comment]
It's a pity that some hardware support libraries have dependencies that have nothing to do with the actual interface. 

However adding python-mako and maybe python-cheetah to the list here: https://github.com/f4exb/sdrangel/blob/master/.appveyor.yml#L67 should suffice. 

For Windows it may indeed be easier to use pre-built binaries.

Alternatively the UHD support can be excluded from package builds and available only if compiled from source.

**Comment by srcejon** [comment]
Thanks, I'll take a look.

For Windows, I have added the binary release to sdrangel-windows-libraries

**Comment by srcejon** [comment]
Sorry, a bit of trial-and-error there. It works, but very close to 1h.

I see Debian actually has a pre-built UHD package that just can be installed with 'sudo apt-get install libuhd-dev'. That would speed it up, but I don't know how you prefer to manage the dependencies.

**Comment by f4exb** [comment]
Yes for the package build it could be better to use the Debian package libuhd-dev.

**Pull request merged**
